### ISSUE TITLE
Channel Combinations

### ISSUE THREAD

**Issue by andreastyro** [Telecominfraproject/oopt-gnpy#456]
Hello, 

I am creating an API using GNPy. I want to test the different combinations of channels and their performance. So far, I have managed to create the combinations on OMS object that are in an OMS list. However, I want to input these channel combinations when using the gnpy-transmission-example command so that the combinations I implemented are used and not the ones on the .json file that is inputted.

What should be my course of action?

Kind regards,
Andreas Tyrovolas

**Comment by jktjkt** [comment]
Hi @andreastyro , if you're using the console applications such as `gnpy-transmission-example`, the input spectrum is defined through the JSON file via the [`SI` block](https://gnpy.readthedocs.io/en/master/json.html#spectralinformation) in `eqpt-config.json`. Since the latest release we've made it possible to [specify a mixed channel load for propagation](https://gnpy.readthedocs.io/en/master/json.html#arbitrary-channel-definition). That's the load which will be used for simulation over all links -- and it will be the same mapping of all channels used over all links because there's currently no non-programmer way of specifying a vastly different channel load over different parts of the network (are you interested in something like that?).

I'm a bit confused by your mention of creating the OMS objects by hand, though. Are you starting this simulation through some custom Python code, perhaps?

My apologies for a late reply, I managed to overlook this bugreport.

**Comment by akhil-mutike** [comment]
hi @jktjkt ,iam exactly looking for channel configuration you mentioned in above comment.i,.e.. i want to specify mixed channel load for each link seperaterly...will that be availiable in near future?

**Comment by abhiman84** [comment]
Hi,

I modified the SI block as follows:


     "SI":[{
            "f_min": 191.3e12,
            "baud_rate": 32e9,
            "f_max":192.1e12,
            "spacing": 50e9,
            "power_dbm": 0,
            "power_range_db": [0,0,1],
            "roll_off": 0.15,
            "tx_osnr": 40,
            "sys_margins": 2
            },{
            "f_min": 193.3e12,
            "baud_rate": 32e9,
            "f_max":194.1e12,
            "spacing": 50e9,
            "power_dbm": 0,
            "power_range_db": [0,0,1],
            "roll_off": 0.15,
            "tx_osnr": 40,
            "sys_margins": 2
            }
      ],

I get the following error: 

 gnpy-transmission-example $(gnpy-example-data)/raman_edfa_example_network.json --sim $(gnpy-example-data)/sim_params.json --show-channels 
There are 16 channels propagating
Power mode is set to True
=> it can be modified in eqpt_config.json - Span
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "/usr/local/bin/gnpy-transmission-example", line 8, in <module>
    sys.exit(transmission_main_example())
  File "/usr/local/lib/python3.9/site-packages/gnpy/tools/cli_examples.py", line 243, in transmission_main_example
    design_network(ref_req, network, equipment, set_connector_losses=True, verbose=True)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 775, in design_network
    build_network(network, equipment, pref_ch_db, pref_total_db, set_connector_losses=set_connector_losses,
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 762, in build_network
    set_egress_amplifier(network, roadm, equipment, pref_ch_db, pref_total_db, verbose)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 318, in set_egress_amplifier
    node_loss = span_loss(network, prev_node, equipment)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 244, in span_loss
    gain += sum(estimate_raman_gain(n, equipment) for n in prev_node_generator(network, node))
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 244, in <genexpr>
    gain += sum(estimate_raman_gain(n, equipment) for n in prev_node_generator(network, node))
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/network.py", line 229, in estimate_raman_gain
    spectral_info_out = n_copy(spectral_info_input)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/elements.py", line 676, in __call__
    self.propagate(spectral_info)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/elements.py", line 724, in propagate
    spectral_info.nli += NliSolver.compute_nli(spectral_info, stimulated_raman_scattering, self)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/science_utils.py", line 311, in compute_nli
    eta = NliSolver._ggn_spectrally_separated(cut_indices, spectral_info, fiber, srs)
  File "/usr/local/lib/python3.9/site-packages/gnpy/core/science_utils.py", line 392, in _ggn_spectrally_separated
    gamma = outer(fiber.gamma(frequency[cut_indices]), ones(nch))
IndexError: index 17 is out of bounds for axis 0 with size 16

I got same error when using -spectrum option and specifying the same channels.
Kindly guide !
